
## Simple Linear Regression using sklearn

In [2]:
import pandas as pd
import numpy as np
# from sklearn.datasets import load_boston

In [ ]:
# boston = load_boston()

In [ ]:
# print(boston.data.shape, boston.target.shape, boston.feature_names.shape)
# print(type(boston.data), type(boston.target), type(boston.feature_names))

In [ ]:
# boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
# boston_df['MEDV'] = boston.target
# boston_df.head()

In [3]:
boston_df = pd.read_csv('boston.csv')
print(boston_df.shape)
boston_df.head()

(506, 16)

,TOWN,TRACT,LON,LAT,MEDV,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO
0,Nahant,2011,-70.955,42.2550,24.0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3
1,Swampscott,2021,-70.950,42.2875,21.6,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8
2,Swampscott,2022,-70.936,42.2830,34.7,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8
3,Marblehead,2031,-70.928,42.2930,33.4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7
4,Marblehead,2032,-70.922,42.2980,36.2,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7

**X**
* CRIM per capita crime rate by town
* ZN proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS proportion of non-retail business acres per town
* CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
* NOX nitric oxides concentration (parts per 10 million)
* RM average number of rooms per dwelling
* AGE proportion of owner-occupied units built prior to 1940
* DIS weighted distances to five Boston employment centres
* RAD index of accessibility to radial highways
* TAX full-value property-tax rate per USD 10,000
* PTRATIO pupil-teacher ratio by town
* B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
* LSTAT % lower status of the population

**Y**
* MEDV Median value of owner-occupied homes in USD 1000’s

In [4]:
import seaborn as sns
%matplotlib inline
import matplotlib.pyplot as plt

## Simple Linear Regression

In [ ]:
X1 = boston_df[['INDUS','DIS','RM','CRIM']]
y = boston_df.MEDV

In [7]:

print(X1.shape, y.shape)
X1.head()

(506, 4) (506,)

   INDUS     DIS     RM     CRIM
0   2.31  4.0900  6.575  0.00632
1   7.07  4.9671  6.421  0.02731
2   7.07  4.9671  7.185  0.02729
3   2.18  6.0622  6.998  0.03237
4   2.18  6.0622  7.147  0.06905

In [8]:
# Use only one feature RM - Average no of rooms
from sklearn.linear_model import LinearRegression
slm1 = LinearRegression()
slm1.fit(X1, y) # fit the model
print("Coefficient (m):", slm1.coef_,"Intercept (c):", slm1.intercept_)

Coefficient (m): [-0.37351122 -0.62579058  7.46788604 -0.21917921] Intercept (c): -17.077456687880396

In [9]:
predicted_1 = slm1.predict(X1) # Predict prices
print("Predicted values: ", predicted_1[:4])
print("Actual values:\n", boston_df[['MEDV']][:4])

Predicted values:  [28.60021446 25.11876511 30.82423443 30.56779292]
Actual values:
    MEDV
0  24.0
1  21.6
2  34.7
3  33.4

In [10]:
type(predicted_1)

numpy.ndarray